# Docker compose file that builds images and runs the containers needed for
# development. You need to have your MJKEY set in the environment.
#
# docker-compose \
#     -f ./docker/docker-compose.dev.yml \
#     build \
#         --build-arg MJKEY="$(cat ~/.mujoco/mjkey.txt)"

version: "2.4"
services:
  avi-softlearning-dev-gpu:
    image: mjgpu:latest
    container_name: frederikscontainer_mjgpu
    runtime: nvidia
    build:
      context: ../.
      dockerfile: mj_gpu_docker/Dockerfile.softlearning.base.gpu
      args:
        - MJKEY
    working_dir: /home
    environment:
      - DISPLAY=:0
      - RECPLAN_DATA_DIR=/home/recplan_data/
      - RECPLAN_INSTALL_DIR=/home/recursive_planning/
      - RECPLAN_EXP_DIR=/home/experiments/
    ports:
      - "6006"  # Tensorboard
      - "8888"  # Jupyter
    volumes:
       - ~/.mujoco/mjkey.txt:/root/.mujoco/mjkey.txt  # mjkey.txt
       - /:/parent
       - ${RECPLAN_DATA_DIR}:/home/recplan_data
       - ${RECPLAN_INSTALL_DIR}/:/home/recursive_planning
       - ${RECPLAN_EXP_DIR}/:/home/experiments
    command:
      - bash
    stdin_open: true
    tty: true
